### ISSUE TITLE
gfx_math_sinpi doesn't use the first row (Y=0)

### ISSUE THREAD

**Issue by vifino** [vifino/sled#10]
While it looks awesome now, it doesn't use the first row, which is fine on high resolution matrices, but things with, say, just 8 pixels in the Y axis really want that extra pixel.

@marenz2569 perhaps this is a fix you'd like to do? :)

**Comment by marenz2569** [comment]
I have actually seen this too. I'll take a look.

**Comment by marenz2569** [comment]
a few hours later... it works
