### ISSUE TITLE
CI/CD for sled

### ISSUE THREAD

**Issue by vifino** [vifino/sled#12]
Having a service such as Travis continuously build and test sled on each commit would be quite handy.

Checklist to full testing:
* [x] Build on each commit.
* [x] Implement a sled dummy benchmark backend, where `wait_until`  does nothing.
* [x] Implement a sled mode where, instead of randomly queuing modules, every module gets run sequentially, then deinit after a few rounds.
* [x] Report status back to GitHub, including errors and warnings.
* [x] ASAN.

**Comment by fridtjof** [comment]
We could try out Travis CI, it's free for open repos 🤔

**Comment by fridtjof** [comment]
https://github.com/vifino/sled/blob/ac4c00355f06d24af50112e51d39352e2a0d5dea/src/main.c#L62-L67

Is there a reason to calculate this again every time? Doesn't matter very much performance wise, but it could be extracted to make implementing similar modes for queueing modules easier.

**Comment by vifino** [comment]
Probably not.

**Comment by vifino** [comment]
So, @fridtjof, you wanna do this? :)

Travis is perfect.
Would be nice if you could do a functional test and such. Many thanks!

**Comment by fridtjof** [comment]
You'll have to set up travis as the repo owner and give me access :)

**Comment by vifino** [comment]
I set it up, you just need to write a travis.yml
