### ISSUE TITLE
Request for exemplary part list

### ISSUE THREAD

**Issue by kafussl** [vifino/sled#3]
Hi,
can you write down a exemplary list of parts on needs for sled or for your original configuration so that hard- and software are working together?

Thanks in advance,

**Comment by vifino** [comment]
Hey. I finally found the time to write the hardware side down, should be everything important.

This is the one I showed at Easterhegg 2018: https://github.com/vifino/sled/wiki/Hardware:-vifino's-Easterhegg-2018-64x64-matrix

Software side setup (and maybe even a ready to use image) will follow in detail another time.

Let me know if you have any questions or suggestions for the wiki.
