### ISSUE TITLE
gfx_candyflow crash on macOS.

### ISSUE THREAD

**Issue by vifino** [vifino/sled#36]
When run on macOS, it complains about the lack of the symbol `_perf_start`.

Error:
```
>> Now drawing candyflowdyld: lazy symbol binding failed: Symbol not found: _perf_start
  Referenced from: /Users/vifino/src/sled/./modules/gfx_candyflow.so
  Expected in: flat namespace

dyld: Symbol not found: _perf_start
  Referenced from: /Users/vifino/src/sled/./modules/gfx_candyflow.so
  Expected in: flat namespace

zsh: abort      ./sled
```

**Comment by vifino** [comment]
@orithena If you could have a look at why that happens, I'd appreciate it.

**Comment by vifino** [comment]
`gfx_affinematrix` also has this problem.

**Comment by vifino** [comment]
I fixed that with lost symbol by marking it static: As it's simply included then, this is fine.

However, now it complains about another missing symbol..

```
>> Now drawing affinematrixdyld: lazy symbol binding failed: Symbol not found: _multm3v2_partx
  Referenced from: /Users/vifino/src/sled/./modules/gfx_affinematrix.so
  Expected in: flat namespace

dyld: Symbol not found: _multm3v2_partx
  Referenced from: /Users/vifino/src/sled/./modules/gfx_affinematrix.so
  Expected in: flat namespace

zsh: abort      ./sled
```

**Comment by vifino** [comment]
Unsurprisingly, it was the same issue of function being defined in a header, with another `static` it's fixed. I'll push it.

**Comment by vifino** [comment]
Oh, you already fixed it, thanks @orithena!

**Comment by orithena** [comment]
@vifino: Yeah, it came up on linux when compiling with -O0 to get a full backtrace for #35 without variables being optimized out ^^

**Comment by vifino** [comment]
Ah, excellent, so it wasn't just macOS being weird, great!
