### ISSUE TITLE
bgm_pixelflut performance improvements

### ISSUE THREAD

**Issue by vifino** [vifino/sled#38]
We might wanna improve the pixelflut performance.
Once #33 is fixed, we can implement a multithreaded pixelflut server like [Pixel](https://github.com/larsmm/pixelflut).

This would allow us to run probably quite a bit faster.
If we implement some network abstractions, it'll be portable as well.

After we get the taskpool working and merged, I'll comb through the pixelflut server and try to make it as fast as I can.

**Comment by fridtjof** [comment]
This isn't done yet

**Comment by vifino** [comment]
oof, weird, it closed it.

**Comment by fridtjof** [comment]
@20kdc removed the OFFSET command and related fields in the px_buffer_t struct in 6ca049a1d382b88147e467b13ffc5dffea71debe

Was there a reason for this? We should bring it back otherwise

**Comment by fridtjof** [comment]
Also, for some dumb (Apple...) reason, macOS does not have MSG_NOSIGNAL (which was added in 88fb4722e43316c79f3b3f216b5568bfd7ff0362), but instead has an equivalent called SO_NOSIGPIPE: https://lists.apple.com/archives/macnetworkprog/2002/Dec/msg00091.html

**Comment by fridtjof** [comment]
fixed in f543304fb525170c14f0e78cbacde30959674e67

**Comment by vifino** [comment]
With #42 being merged, this is done!!
