### ISSUE TITLE
bgm_opc seems to deadlock on deinit

### ISSUE THREAD

**Issue by vifino** [vifino/sled#6]
Seems to be more likely on some platforms than others. Easily reproducable on OSX, seems to happen quite often on BSD, but not always on Linux?

* [X] Temporary hotfix with a "panic" handler, 3 ^C = instant exit!
* [ ] Fix the deadlock in bgm_opc.

@20kdc You should take a look at this.

**Comment by vifino** [comment]
Note: This issue was there before #5, but you could still double ^C to get out most of the time.

A temporary fix is a "panic ^C handler", one that keeps track of the amount of times ^C was pressed, first time is graceful deinit, second is a warning and third is `exit(1)`.

**Comment by marenz2569** [comment]
I have actually seen the same problem happen on Debian Buster, but as I am not using bgm_opc I did not bother and just deleted the shared library after every build.

**Comment by vifino** [comment]
I added the panic handler now, it's working.

**Comment by vifino** [comment]
As of 7d4aafd772ee580feaf9eb4145d4833187566a02, @20kdc fixed this!
They're awesome.
